import type { AIProviderConfig } from "./types";

export const AI_PROVIDERS: Record<string, AIProviderConfig> = {
  openai: {
    id: "openai",
    name: "OpenAI",
    icon: "/providers/openai.svg",
    color: "bg-green-500",
    models: [
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
      "gpt-5.1",
      "gpt-4.1",
      "o3-deep-research",
      "o4-mini-deep-research",
    ],
    defaultModel: "gpt-5.6-terra",
  },
  claude: {
    id: "claude",
    name: "Claude",
    icon: "/providers/claude.svg",
    color: "bg-orange-500",
    models: [
      "claude-opus-5",
      "claude-opus-4-8",
      "claude-opus-4-6",
      "claude-sonnet-5",
      "claude-sonnet-4-6",
      "claude-haiku-4-5-20251001",
    ],
    defaultModel: "claude-sonnet-4-6",
  },
  gemini: {
    id: "gemini",
    name: "Gemini",
    icon: "/providers/gemini.svg",
    color: "bg-blue-500",
    models: [
      "gemini-3.8-flash",
      "gemini-3.7-flash",
      "gemini-3.6-flash",
      "gemini-3.5-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.1-flash-lite",
    ],
    defaultModel: "gemini-3.6-flash",
  },
  grok: {
    id: "grok",
    name: "Grok",
    icon: "/providers/grok.svg",
    color: "bg-gray-500",
    models: ["grok-4.6", "grok-4.5", "grok-4.3", "grok-build-0.1"],
    defaultModel: "grok-4.6",
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    icon: "/providers/deepseek.svg",
    color: "bg-purple-500",
    models: ["deepseek-v4-flash", "deepseek-v4-pro"],
    defaultModel: "deepseek-v4-flash",
  },
  perplexity: {
    id: "perplexity",
    name: "Perplexity",
    icon: "/providers/perplexity.svg",
    color: "bg-indigo-500",
    models: ["sonar-pro", "sonar"],
    defaultModel: "sonar-pro",
  },
};
